### ISSUE TITLE
`cqcp_m5()`: fails with spatial buddies in range

### ISSUE THREAD

**Issue by falk-env** [dafenner/CrowdQCplus#29]
Unfortunately, running `cqcp_qcCWS()` on a Netatmo data sample fails currently with:

```
[CrowdQC+] QC level m5 could not meaningfully be performed with current configuration 
(only isolated stations with too few buddies). All flags m5 = FALSE. 
Consider increasing the radius, decreasing the number of buddies, or setting 'keep_isolated = TRUE'.
```

This does not seem to be correct since there are a lot of neighbouring stations nearby but the call even fails with e.g. `m5_radius = 10000` and `m5_n_buddies = 1`. 

![netatmo_essen](https://user-images.githubusercontent.com/78563765/199683399-da853b2f-f9a8-48bd-b4a5-19103e5cd6d5.png)

Data can temporarily be accessed at [falk-env/share](https://github.com/falk-env/share/tree/main/data) and consists of:

- stations.rda - sf object containing stations and some metadata, but most importantly locations.
- dt_pad.rda - data.table according to requirements after `cqcp_padding()`, passes `cqcp_check_input()` without issues.

Is this a layer 8 issue or something not working properly with distances here? Thanks!

**Comment by dafenner** [comment]
Thanks for pointing this out and the data.

I've checked what's going on and the problem is actually with the format of the `p_id` column and https://github.com/dafenner/CrowdQCplus/blob/4f95e7b2647e5a3bacf714ee70f2ac610ab6eab9/R/cqcp_filter.R#L379

The conversion doesn't make sense with the type of `p_id` you have (strings/characters) and leads to the error.
I usually have integers for that column and keep Netatmo IDs in a separate one.

As a quick workaround I suggest you simply add a new type of `p_id` with integers: 

```
unique <- unique(dt_pad$p_id)
setnames(dt_pad, "p_id", "id")
dt_pad[, p_id := NA]
for(i in seq(1, length(unique))) dt_pad[dt_pad$id == unique[i]]$p_id <- i
```

Afterwards QC level m5 should work without errors.

I will consider removing this conversion (could increase overall time for larger data sets) or improve documentation and `cqcp_check_input` (#30) in the next fix.

**Comment by dafenner** [comment]
Let me know if this also works for you.

As a side note @falk-env : I noticed that you have start and end times not corresponding to beginning and end of a month, respectively. This is not a problem, yet in QC levels m3 and m4 a monthly basis is used per default. Hence you have three periods of quite unequal length for the checks. 
Consider using a different length of the episode for checking (e.g. 22 days in your case, splitting your period in half) or simply use parameter `complete = TRUE` in `cqcp_m3` and `cqcp_m4`

**Comment by falk-env** [comment]
Argh, should have checked that before raising an issue - thanks! Works fine now with integer values as `p_id`. Best thing is, it requires just some rather trivial adjustments during pre-processing.

Also, thanks for the side note - will consider this, but this will require some more efforts beforehand, like merging several sub-datasets, eventually removing duplicates and subsetting to full months. At the moment, I just crawled some random data to play around with.
