### ISSUE TITLE
m2 level

### ISSUE THREAD

**Issue by reemeslam13** [dafenner/CrowdQCplus#39]
I do not understand in m2 level how CrowdQC+ exclude values, do u consider PRWS? or do u check surrounding temperature values i could not understand this part in the paper

**Comment by dafenner** [comment]
Hi @reemeslam13 .
Actually, the whole QC works without any additional weather-station data, so every QC level just takes data from the data set itself and exploits the "wisdom of the crowd". That's why having more stations generally provides more robust results.
In QC level m2 we use the whole data set (all stations that passed QC level m1) at every time step and basically check the distribution function of values. Any values that exceed the defined thresholds for the upper and lower ends of the distribution are flagged.
Column "z" is indeed the elevation/altitude information for each station, used to normalize the temperature values to a common height if `heightCorrection = TRUE` using the specified `lapse_rate`.

The surrounding stations (within a radius) are used in QC level m5, the "buddy check".

**Comment by reemeslam13** [comment]
And how do you calculate the threshold ? do use the temperature relation between stations based on longitude and latitude  on calculating  the threshold ?

sorry if i am asking a lot of questions ,
Thanks in advance.

**Comment by dafenner** [comment]
The threshold is not calculated dynamically. We set the threshold to 0.95 for the upper end of the distribution and 0.01 per default, but that can be changed using the parameters "high" and "low". It basically determines how much of the distribution (how many values) at the upper and lower ends of the distribution you discard during this QC level. Setting a lower threshold for the upper end (e.g. `high=0.9`) and a higher value for the lower end (e.g. `low=0.1`), e.g., you are stricter with your filtering.
You can also have a look at the [Napoly et al. (2018) paper](https://doi.org/10.3389/feart.2018.00118), sections "Main QC Levels" and especially "Sensitivity Tests", to get some further details on those values.

**Comment by dafenner** [comment]
I will close this issue now. @reemeslam13 let me know if you want to reopen it.
